
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework
spec:
  storageClassName: "homework-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
