apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  namespace: homework
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
        add: ["SYS_PTRACE"]
  - name: debugger
    image: nicolaka/netshoot
    command: ["/bin/sleep", "infinity"]
    securityContext:
      capabilities:
        add: ["SYS_PTRACE"]
      runAsUser: 0
      privileged: false
