releases:
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: 26.7.1
    values:
      - kRaft:
          enabled: true
          controller:
            replicaCount: 3
        replicaCount: 5
        image:
          tag: 3.5.2-debian-11-r0
        auth:
          enabled: false
          clientProtocol: SASL_PLAINTEXT
          sasl:
            mechanisms: PLAIN
            interBrokerMechanism: PLAIN
          existingSecret: kafka-credentials
        persistence:
          enabled: false
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m

  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    version: 26.7.1
    values:
      - kRaft:
          enabled: true
          controller:
            replicaCount: 1
        replicaCount: 1
        auth:
          enabled: false
          clientProtocol: PLAINTEXT
        persistence:
          enabled: false
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m
