
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-chart.fullname" . }}-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
