apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-admin-binding
  namespace: {{ .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: cd
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io