apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-chart.selectorLabels" . | nindent 4 }}
