apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks-app
  namespace: argo-cd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-04OTUS/d.zimin_repo.git
    targetRevision: HEAD
    path: kubernetes-networks
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
    - CreateNamespace=true