apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus
  namespace: argo-cd
spec:
  description: "Project for OTUS homework"
  sourceRepos:
  - "https://github.com/Kuber-2025-04OTUS/d.zimin_repo.git"
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

