apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nginx-metrics
  namespaceSelector:
    matchNames:
    - homework
  endpoints:
  - port: metrics
    interval: 15s
