apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  namespace: homework
  labels:
    app: nginx-metrics
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
  selector:
    app: nginx-metrics
