loki:
  auth_enabled: false

  nodeSelector:
    role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2025-06-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: ru-central1
      bucketnames: loki-logs-s3-homework
      s3forcepathstyle: false
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 10h # 28 days retention

  storage:
    type: s3
    bucketNames:
        chunks: loki-logs
        ruler: loki-logs
        admin: loki-log
    s3:
      # AWS endpoint URL
      endpoint: storage.yandexcloud.net
      # AWS region where the S3 bucket is located
      region: ru-central1
      # AWS secret access key
      secretAccessKey:
      # AWS access key ID
      accessKeyId:
      # AWS signature version (e.g., v2 or v4)
      signatureVersion: v4
      # Forces the path style for S3 (true/false)
      s3ForcePathStyle: false
      # Allows insecure (HTTP) connections (true/false)
      insecure: false
      # HTTP configuration settings
      http_config: {}

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  # resources:
  #   limits:
  #     cpu: 3
  #     memory: 4Gi
  #   requests:
  #     cpu: 2
  #     memory: 2Gi
  extraEnv:
    # Keep a little bit lower than memory limits
    - name: GOMEMLIMIT
      value: 3750MiB

chunkCache:
  enabled: false
  allocatedMemory: 10MB

# Disable minio storage
minio:
  enabled: false

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
  max_concurrent: 2
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

gateway:
  nodeSelector:
    role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

lokiCanary:
  nodeSelector:
    role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

chunksCache:
  nodeSelector:
    role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

resultsCache:
  nodeSelector:
    role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"