apiVersion: v1
kind: Pod
metadata:
  name: k8s-intro
  namespace: homework
spec:
  volumes:
    - name: workdir
      emptyDir: {}
  initContainers:
    - name: init-container
      image: busybox:1.28
      command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://info.cern.ch
      volumeMounts:
        - name: workdir
          mountPath: /init
  containers:
    - name: web-server
      image: nginx
      command: ["/bin/sh", "-c"]
      args:
        - >
          sed -i 's/listen  .*/listen 8000;/g' /etc/nginx/conf.d/default.conf &&
          sed -i 's|root\s\+.*|root /homework;|g' /etc/nginx/conf.d/default.conf &&
          exec nginx -g 'daemon off;'
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: workdir
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
